import SigmaOpLaguerreDomains

namespace Sigma
noncomputable section

/-- Every eigenvector equation of the actual unbounded integer operator gives
the corresponding equation at each genuine Hilbert-basis coordinate. -/
theorem laguerre_eigenvector_coordinate (lam : ℂ)
    (x : (laguerreSpectralOperator id).domain)
    (hx : laguerreSpectralOperator id x = lam • x.val) (n : ℕ) :
    (n : ℂ) * laguerreCoefficient x.val n = lam * laguerreCoefficient x.val n := by
  have h := congrArg (fun y : LaguerreWeightedHilbert => laguerreHilbertBasis.repr y n) hx
  dsimp only at h
  rw [laguerre_spectral_coordinate, map_smul] at h
  exact h

theorem laguerre_nonzero_coefficient (x : LaguerreWeightedHilbert) (hx : x ≠ 0) :
    ∃ n : ℕ, laguerreCoefficient x n ≠ 0 := by
  by_contra h
  push_neg at h
  apply hx
  apply laguerreHilbertBasis.repr.injective
  apply lp.ext
  funext n
  simpa only [map_zero, lp.coeFn_zero, Pi.zero_apply] using h n

/-- There are no additional complex eigenvalues. This is a statement about
the actual operator and nonzero domain vectors, not a list of known modes. -/
theorem laguerre_eigenvalue_is_integer (lam : ℂ)
    (x : (laguerreSpectralOperator id).domain) (hne : x.val ≠ 0)
    (hx : laguerreSpectralOperator id x = lam • x.val) :
    ∃ n : ℕ, lam = (n : ℂ) := by
  obtain ⟨n, hn⟩ := laguerre_nonzero_coefficient x.val hne
  exact ⟨n, (mul_right_cancel₀ hn (laguerre_eigenvector_coordinate lam x hx n)).symm⟩

/-- The full eigenspace at `n` is the line generated by the normalized `n`th
Laguerre function; this includes the zero eigenvector and the zero mode. -/
theorem laguerre_integer_eigenvector_line (n : ℕ)
    (x : (laguerreSpectralOperator id).domain)
    (hx : laguerreSpectralOperator id x = (n : ℂ) • x.val) :
    x.val = laguerreCoefficient x.val n • laguerreHilbertBasis n := by
  apply laguerreHilbertBasis.repr.injective
  apply lp.ext
  funext k
  rw [map_smul, laguerreHilbertBasis.repr_self]
  change laguerreCoefficient x.val k =
    laguerreCoefficient x.val n * (lp.single (E := fun _ : ℕ => ℂ) 2 n (1 : ℂ)) k
  by_cases hk : k = n
  · subst k
    simp only [lp.single_apply_self, mul_one]
  · rw [lp.single_apply_ne _ _ _ hk, mul_zero]
    have hc := laguerre_eigenvector_coordinate (n : ℂ) x hx k
    have hkn : (k : ℂ) ≠ (n : ℂ) := by exact_mod_cast hk
    exact (mul_eq_mul_right_iff.mp hc).resolve_left hkn

theorem laguerre_point_spectrum_exact (lam : ℂ) :
    (∃ x : (laguerreSpectralOperator id).domain,
      x.val ≠ 0 ∧ laguerreSpectralOperator id x = lam • x.val) ↔
      ∃ n : ℕ, lam = (n : ℂ) := by
  constructor
  · rintro ⟨x, hne, hx⟩
    exact laguerre_eigenvalue_is_integer lam x hne hx
  · rintro ⟨n, rfl⟩
    exact ⟨⟨laguerreHilbertBasis n, laguerre_basis_mem_spectral_domain id n⟩,
      laguerreHilbertBasis.orthonormal.ne_zero n,
      laguerre_spectral_basis_action id n⟩

/-- Eigenspaces are subspaces of the original weighted complex `L²`, retaining
the domain condition of the unbounded operator. -/
def laguerreIntegerEigenspace (n : ℕ) : Submodule ℂ LaguerreWeightedHilbert where
  carrier := {x | ∃ hx : x ∈ (laguerreSpectralOperator id).domain,
    laguerreSpectralOperator id ⟨x, hx⟩ = (n : ℂ) • x}
  zero_mem' := ⟨Submodule.zero_mem _, by
    change (laguerreSpectralOperator id).toFun 0 = _
    simp⟩
  add_mem' := by
    rintro x y ⟨hx, hAx⟩ ⟨hy, hAy⟩
    refine ⟨Submodule.add_mem _ hx hy, ?_⟩
    change laguerreSpectralOperator id (⟨x, hx⟩ + ⟨y, hy⟩) = _
    rw [LinearPMap.map_add, hAx, hAy, smul_add]
  smul_mem' := by
    rintro c x ⟨hx, hAx⟩
    refine ⟨Submodule.smul_mem _ c hx, ?_⟩
    change laguerreSpectralOperator id (c • ⟨x, hx⟩) = _
    rw [LinearPMap.map_smul, hAx, smul_comm]

theorem laguerre_integer_eigenspace_eq_span (n : ℕ) :
    laguerreIntegerEigenspace n = Submodule.span ℂ {laguerreHilbertBasis n} := by
  apply le_antisymm
  · rintro x ⟨hx, hAx⟩
    have he : x = laguerreCoefficient x n • laguerreHilbertBasis n :=
      laguerre_integer_eigenvector_line n ⟨x, hx⟩ hAx
    rw [he]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (by simp))
  · apply Submodule.span_le.mpr
    intro x hx
    have he : x = laguerreHilbertBasis n := by simpa using hx
    subst x
    exact ⟨laguerre_basis_mem_spectral_domain id n, laguerre_spectral_basis_action id n⟩

theorem laguerre_integer_eigenvalue_simple (n : ℕ) :
    Module.finrank ℂ (laguerreIntegerEigenspace n) = 1 := by
  rw [laguerre_integer_eigenspace_eq_span]
  exact finrank_span_singleton (laguerreHilbertBasis.orthonormal.ne_zero n)

end
end Sigma
