import SigmaRealizations

/-! Kernel dependencies for every realization theorem. -/
#print axioms Sigma.cwLeft_positive
#print axioms Sigma.cwLeft_lt_one
#print axioms Sigma.cwRight_gt_one
#print axioms Sigma.cwLeft_injectiveOn
#print axioms Sigma.cwValue_positive
#print axioms Sigma.cwValue_injective
#print axioms Sigma.cw_parent_below
#print axioms Sigma.cw_parent_above
#print axioms Sigma.cw_reduced_fraction_exists
#print axioms Sigma.cw_positive_rational_exists
#print axioms Sigma.cw_positive_rational_exists_unique
#print axioms Sigma.farey_left_inverse
#print axioms Sigma.farey_right_inverse
#print axioms Sigma.farey_left_range
#print axioms Sigma.farey_right_range
#print axioms Sigma.placed_collision_iff
#print axioms Sigma.collisionScaleDifference_deriv
#print axioms Sigma.collisionScaleDifference_strictAnti
#print axioms Sigma.every_placed_collision_breaks_multiplication
#print axioms Sigma.intrinsic_alternative_strictAnti
#print axioms Sigma.intrinsic_alternative_injective
#print axioms Sigma.transportedProduct_encode
#print axioms Sigma.transportedProduct_assoc
#print axioms Sigma.transportedProduct_comm
#print axioms Sigma.transportedUnit_mul
#print axioms Sigma.transported_divisibility
#print axioms Sigma.formal_shift_mul_X
#print axioms Sigma.formal_exponential_mul
#print axioms Sigma.formal_exponential_rescale
#print axioms Sigma.formal_exponential_inverse_product
#print axioms Sigma.formal_exponential_coeff_one
#print axioms Sigma.formal_exponential_sub_one_ne_zero
#print axioms Sigma.rescaled_todd_quotient
#print axioms Sigma.ahat_denominator_constant
#print axioms Sigma.ahat_denominator_mul_X
#print axioms Sigma.formal_ahat_constant
#print axioms Sigma.formal_ahat_quotient
#print axioms Sigma.l_denominator_constant
#print axioms Sigma.l_denominator_mul_X
#print axioms Sigma.formal_L_constant
#print axioms Sigma.formal_L_quotient
#print axioms Sigma.formal_ahat_to_todd
#print axioms Sigma.formal_todd_to_ahat
#print axioms Sigma.formal_todd_to_L
#print axioms Sigma.formal_L_to_todd
#print axioms Sigma.rational_series_map_rescale
#print axioms Sigma.rational_series_map_constant
#print axioms Sigma.formal_ahat_over_constant
#print axioms Sigma.formal_L_over_constant
#print axioms Sigma.formal_ahat_over_quotient
#print axioms Sigma.formal_L_over_quotient
#print axioms Sigma.formal_ahat_over_to_todd
#print axioms Sigma.formal_todd_over_to_L
#print axioms Sigma.formal_L_over_to_todd
#print axioms Sigma.formal_ahat_over_square_root_constant
#print axioms Sigma.formal_ahat_over_square_root_equation
#print axioms Sigma.normalized_square_root_unique_over_Q_algebra
#print axioms Sigma.formal_ahat_over_square_root_exists_unique
#print axioms Sigma.formal_ahat_over_square_root_recovers_todd
#print axioms Sigma.formal_chi_over_constant
#print axioms Sigma.formal_exponential_over_rescale
#print axioms Sigma.rescaled_todd_over_quotient
#print axioms Sigma.formal_chi_over_quotient_product
#print axioms Sigma.formal_chi_over_recovers_todd
#print axioms Sigma.formal_chi_over_minus_one
#print axioms Sigma.formal_todd_over_exponential_denominator
#print axioms Sigma.formal_L_over_exponential_denominator
#print axioms Sigma.formal_todd_over_recovers_exponential
#print axioms Sigma.formal_L_over_recovers_exponential
#print axioms Sigma.standard_characteristic_units_inverse_reconstruction
#print axioms Sigma.formal_chi_constant
#print axioms Sigma.chi_denominator_constant
#print axioms Sigma.chi_denominator_mul_X
#print axioms Sigma.formal_chi_quotient_product
#print axioms Sigma.formal_chi_standard_quotient
#print axioms Sigma.characteristic_chi_Todd_inverse
#print axioms Sigma.characteristic_Todd_chi_inverse
#print axioms Sigma.formal_chi_recovers_todd
#print axioms Sigma.characteristic_chi_minus_one
#print axioms Sigma.formal_chi_minus_one_standard
#print axioms Sigma.characteristic_chi_minus_one_noninjective
#print axioms Sigma.localized_characteristic_parameter_unit
#print axioms Sigma.formal_chi_polynomial_localization_reconstruction
#print axioms Sigma.formal_ahat_inverse_denominator
#print axioms Sigma.formal_ahat_b
#print axioms Sigma.formal_ahat_square_root_constant
#print axioms Sigma.formal_ahat_square_root_equation
#print axioms Sigma.normalized_formal_square_root_unique
#print axioms Sigma.formal_ahat_square_root_exists_unique
#print axioms Sigma.formal_ahat_square_root_reconstruction
#print axioms Sigma.formal_ahat_square_root_recovers_todd
#print axioms Sigma.formal_ahat_recovers_todd_from_any_normalized_root
#print axioms Sigma.formal_L_exponential_recovery_product
#print axioms Sigma.formal_L_recovers_exponential
#print axioms Sigma.field_tower_coefficient_zero
#print axioms Sigma.field_tower_solution_constant
#print axioms Sigma.field_tower_solution_observation
#print axioms Sigma.normalized_field_tower_observations_injective
#print axioms Sigma.complete_field_tower_exists_unique
#print axioms Sigma.unnormalized_todd_constant
#print axioms Sigma.unnormalized_todd_observation
#print axioms Sigma.unnormalized_todd_family_exists_unique
#print axioms Sigma.unnormalized_todd_parameter_injective
#print axioms Sigma.algebra_tower_coefficient_zero
#print axioms Sigma.algebra_tower_solution_constant
#print axioms Sigma.rational_successor_inverse
#print axioms Sigma.algebra_tower_solution_observation
#print axioms Sigma.normalized_algebra_tower_observations_injective
#print axioms Sigma.complete_algebra_tower_exists_unique
#print axioms Sigma.unnormalized_todd_over_constant
#print axioms Sigma.unnormalized_todd_over_observation
#print axioms Sigma.unnormalized_todd_family_over_Q_algebra_exists_unique
#print axioms Sigma.unnormalized_todd_over_parameter_injective
#print axioms Sigma.unit_chi_left_inverse
#print axioms Sigma.unit_chi_right_inverse
#print axioms Sigma.characteristic_chi_recovery_of_unit
#print axioms Sigma.characteristic_chi_recovery_unit_condition
#print axioms Sigma.normalized_series_inverse_involution
#print axioms Sigma.standard_characteristic_inverse_reconstruction
#print axioms Sigma.matrix_trace_eq_eigenvalue_sum
#print axioms Sigma.matrixPotential_spectral
#print axioms Sigma.matrixPotential_nonnegative
#print axioms Sigma.matrixPotential_eq_zero_iff
#print axioms Sigma.spd_determinant_exponential_bound
#print axioms Sigma.spd_determinant_exponential_equality
#print axioms Sigma.spd_scalar_block_lift_unique
#print axioms Sigma.spd_positive_rank_lift_unique
#print axioms Sigma.matrix_bregman_formula
#print axioms Sigma.matrix_precision_reversal
#print axioms Sigma.precisionMetric_symmetric
#print axioms Sigma.symmetric_trace_square
#print axioms Sigma.symmetric_trace_square_nonnegative
#print axioms Sigma.positive_definite_congruence
#print axioms Sigma.sqrt_positive_definite_isUnit
#print axioms Sigma.matrixDivergence_relative_potential
#print axioms Sigma.matrixDivergence_nonnegative
#print axioms Sigma.matrixDivergence_self
#print axioms Sigma.matrixDivergence_eq_zero_iff
#print axioms Sigma.precisionMetric_nonnegative
#print axioms Sigma.matrixPotential_similarity
#print axioms Sigma.matrix_relative_congruence
#print axioms Sigma.matrixDivergence_congruence
#print axioms Sigma.perpendicular_equal_norm_from_pair
#print axioms Sigma.even_nonnegative_orthogonal_quadratic
#print axioms Sigma.quadratically_bounded_doubling_zero
#print axioms Sigma.nonnegative_orthogonal_quadratic_of_pair
#print axioms Sigma.nonnegative_orthogonal_quadratic_finiteDimensional
#print axioms Sigma.nonnegative_orthogonal_quadratic
#print axioms Sigma.nonnegative_orthogonal_quadratic_iff
#print axioms Sigma.quartic_not_orthogonal_additive_of_pair
#print axioms Sigma.line_quartic_orthogonal_additive
#print axioms Sigma.line_quartic_not_quadratic
#print axioms Sigma.nonnegative_orthogonal_star_finiteDimensional
#print axioms Sigma.nonnegative_orthogonal_star
#print axioms Sigma.nonnegative_orthogonal_star_iff
#print axioms Sigma.quadratic_scale_calibration
#print axioms Sigma.quadratic_nontrivial_scale_positive
#print axioms Sigma.towerCoefficient_zero
#print axioms Sigma.towerSolution_constant
#print axioms Sigma.towerSolution_observation
#print axioms Sigma.complete_tower_exists_unique
#print axioms Sigma.todd_tower_exists_unique
#print axioms Sigma.degree_zero_tower_is_normalization
#print axioms Sigma.omitted_todd_degree
#print axioms Sigma.formal_L_Todd_inverse
#print axioms Sigma.formal_Todd_L_inverse
#print axioms Sigma.formal_chi_Todd_inverse
#print axioms Sigma.formal_Todd_chi_inverse
#print axioms Sigma.formal_chi_minus_one
#print axioms Sigma.formal_chi_reconstruction_iff
#print axioms Sigma.universal_line_correction_unique
#print axioms Sigma.universal_unit_inverse_reconstruction
#print axioms Sigma.radialWeight_eq_rpow
#print axioms Sigma.radialWeight_pos
#print axioms Sigma.radialWeight_deriv
#print axioms Sigma.weighted_profile_deriv
#print axioms Sigma.weighted_profile_second_deriv
#print axioms Sigma.radial_residual
#print axioms Sigma.radial_laplacian_conjugation
#print axioms Sigma.radial_residual_cancellation
#print axioms Sigma.radial_residual_dimension_three
#print axioms Sigma.radial_OU_dimension
#print axioms Sigma.constant_profile_radial_residual_three
#print axioms Sigma.constant_profile_differs_from_H_on_positive_ray
#print axioms Sigma.nonnegative_additive_ray_linear
#print axioms Sigma.linear_profile_orthogonally_additive
#print axioms Sigma.linear_profile_negative_at_neg_unit
#print axioms Sigma.linear_profile_not_quadratic
#print axioms Sigma.orthogonal_zero
#print axioms Sigma.even_orthogonal_equal_norm
#print axioms Sigma.odd_orthogonal_double
#print axioms Sigma.norm_square_orthogonal_additive
#print axioms Sigma.orthogonal_star_log
#print axioms Sigma.formal_exponential_constant
#print axioms Sigma.formal_exponential_derivative
#print axioms Sigma.todd_denominator_constant
#print axioms Sigma.todd_denominator_mul_X
#print axioms Sigma.todd_denominator_mul_todd
#print axioms Sigma.formal_todd_constant
#print axioms Sigma.formal_todd_quotient_identity
#print axioms Sigma.formal_todd_riccati
#print axioms Sigma.formal_twisted_todd_differential
#print axioms Sigma.formal_twisted_todd_coeff_succ
#print axioms Sigma.formal_twisted_todd_coeff
#print axioms Sigma.formal_exponential_over_map
#print axioms Sigma.formal_todd_over_constant
#print axioms Sigma.formal_todd_over_denominator
#print axioms Sigma.formal_todd_over_quotient_identity
#print axioms Sigma.todd_twist_polynomial_eval_algebra
#print axioms Sigma.formal_twisted_todd_coeff_over_Q_algebra
#print axioms Sigma.formal_todd_tower_over_Q_algebra
#print axioms Sigma.power_difference_over_Q_algebra
#print axioms Sigma.todd_tower_unique_over_Q_algebra
#print axioms Sigma.todd_tower_iff_exponential_quotient_over_Q_algebra
#print axioms Sigma.todd_twist_polynomial_eval
#print axioms Sigma.todd_binomial_polynomial_eval
#print axioms Sigma.todd_twist_polynomial_identity
#print axioms Sigma.formal_exponential_zero
#print axioms Sigma.formal_todd_exponential_recovery_product
#print axioms Sigma.formal_todd_recovers_exponential
#print axioms Sigma.formal_todd_tower
#print axioms Sigma.characteristic_zero_power_difference
#print axioms Sigma.formal_todd_tower_unique
#print axioms Sigma.normalized_todd_tower_iff_exponential_quotient
#print axioms Sigma.all_degree_todd_tower_iff_exponential_quotient
#print axioms Sigma.exponential_quotient_todd_exists_unique
#print axioms Sigma.recursive_todd_equals_exponential_quotient
#print axioms Sigma.formal_todd_omitted_degree
#print axioms Sigma.formal_twisted_todd_coeff_nat
