import SigmaProbGammaProcessDyadic
import SigmaProbGammaProcessIndependence

namespace Sigma
noncomputable section
open MeasureTheory ProbabilityTheory Set
open scoped NNReal ENNReal BigOperators

/-- Sigma algebra generated by the raw splitting variables through row `n`. -/
def gammaDyadicPast {Ω : Type*} (raw : (ℕ × ℕ) → Ω → ℝ) (n : ℕ) : MeasurableSpace Ω :=
  ⨆ i ∈ {i : ℕ × ℕ | i.1 ≤ n}, MeasurableSpace.comap (raw i) inferInstance

def gammaDyadicFresh {Ω : Type*} (raw : (ℕ × ℕ) → Ω → ℝ) (n : ℕ) : MeasurableSpace Ω :=
  ⨆ i ∈ {i : ℕ × ℕ | i.1 = n+1}, MeasurableSpace.comap (raw i) inferInstance

theorem gamma_dyadic_raw_past_measurable {Ω : Type*}
    (raw : (ℕ × ℕ) → Ω → ℝ) (n : ℕ) (i : ℕ × ℕ) (hi : i.1 ≤ n) :
    @Measurable Ω ℝ (gammaDyadicPast raw n) inferInstance (raw i) := by
  apply measurable_iff_comap_le.mpr
  exact le_iSup_of_le i (le_iSup_of_le hi le_rfl)

theorem gamma_dyadic_increment_past_measurable {Ω : Type*}
    (raw : (ℕ × ℕ) → Ω → ℝ) (N n k : ℕ) (hn : n ≤ N) :
    @Measurable Ω ℝ (gammaDyadicPast raw N) inferInstance (gammaDyadicIncrement raw n k) := by
  letI : MeasurableSpace Ω := gammaDyadicPast raw N
  induction n generalizing k with
  | zero => exact gamma_dyadic_raw_past_measurable raw N (0,k) (Nat.zero_le N)
  | succ n ih =>
    change Measurable (fun ω => gammaDyadicIncrement raw n (k/2) ω *
      if k%2=0 then raw (n+1,k/2) ω else 1-raw (n+1,k/2) ω)
    have hp := ih (k/2) (Nat.le_of_succ_le hn)
    have hb := gamma_dyadic_raw_past_measurable raw N (n+1,k/2) hn
    split_ifs
    · exact hp.mul hb
    · exact hp.mul (measurable_const.sub hb)

theorem gamma_dyadic_raw_fresh_measurable {Ω : Type*}
    (raw : (ℕ × ℕ) → Ω → ℝ) (n k : ℕ) :
    @Measurable Ω ℝ (gammaDyadicFresh raw n) inferInstance (raw (n+1,k)) := by
  apply measurable_iff_comap_le.mpr
  exact le_iSup_of_le (n+1,k) (le_iSup_of_le rfl le_rfl)

/-- Previously constructed increments are independent of the next splitting
row because the underlying Haar samples are independent. -/
theorem gamma_dyadic_past_fresh_independent {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (raw : (ℕ × ℕ) → Ω → ℝ)
    (hm : ∀ i, Measurable (raw i)) (hi : iIndepFun (fun _ => inferInstance) raw P) (n : ℕ) :
    Indep (gammaDyadicPast raw n) (gammaDyadicFresh raw n) P := by
  apply indep_iSup_of_disjoint (fun i => (hm i).comap_le) hi
  rw [Set.disjoint_left]
  intro i hi hj
  change i.1 ≤ n at hi
  change i.1 = n+1 at hj
  omega

theorem gamma_dyadic_parent_split_vectors_independent {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (raw : (ℕ × ℕ) → Ω → ℝ)
    (hm : ∀ i, Measurable (raw i)) (hi : iIndepFun (fun _ => inferInstance) raw P) (n K : ℕ) :
    IndepFun (fun ω (k : Fin K) => gammaDyadicIncrement raw n k ω)
      (fun ω (k : Fin K) => raw (n+1,k) ω) P := by
  apply gamma_process_independent_from_sigma P _ _
    (gamma_dyadic_past_fresh_independent P raw hm hi n)
  · letI : MeasurableSpace Ω := gammaDyadicPast raw n
    exact measurable_pi_lambda _ (fun k => gamma_dyadic_increment_past_measurable raw n n k le_rfl)
  · letI : MeasurableSpace Ω := gammaDyadicFresh raw n
    exact measurable_pi_lambda _ (fun k => gamma_dyadic_raw_fresh_measurable raw n k)

end
end Sigma
