import SigmaOpSignedMixing
import SigmaOpResolvent
import SigmaOpSpectral
import Mathlib.Analysis.InnerProductSpace.LinearPMap
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.MeasureTheory.Integral.IntegralEqImproper

/-! Strong Bochner mixing for a genuine contraction evolution generated by a
native partially defined operator.  The generation equations are differential
equations on the full generator domain; neither a mixing identity nor spectral
eigenvector actions are included in this interface.

The construction of such an evolution and of the shift resolvent from an
arbitrary nonnegative self-adjoint operator is a separate obligation.
-/

namespace Sigma
noncomputable section
open MeasureTheory Set Filter
open scoped Topology

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The usual strong contraction evolution and its right generator derivative,
including the right endpoint derivative at zero. -/
structure OpContractionEvolution (B : H →ₗ.[ℂ] H) (S : ℝ → H →L[ℂ] H) : Prop where
  zero_action : ∀ x, S 0 x = x
  contraction : ∀ s, 0 ≤ s → ∀ x, ‖S s x‖ ≤ ‖x‖
  continuous_orbit : ∀ x, ContinuousOn (fun s => S s x) (Ici 0)
  generator_derivative : ∀ (x : B.domain) s, 0 ≤ s →
    HasDerivWithinAt (fun t => S t x.val) (-S s (B x)) (Ici 0) s

theorem op_evolution_shift_derivative (B : H →ₗ.[ℂ] H) (S : ℝ → H →L[ℂ] H)
    (hS : OpContractionEvolution B S) (R : H →L[ℂ] H) (hR : OpIsResolvent B 1 R)
    (x : H) (s : ℝ) (hs : 0 ≤ s) :
    HasDerivWithinAt (fun t => Real.exp (-t) • S t (R x))
      (-(Real.exp (-s) • S s x)) (Ici 0) s := by
  have hd := ((hasDerivAt_id s).neg.exp.hasDerivWithinAt).smul
    (hS.generator_derivative ⟨R x,hR.image_mem x⟩ s hs)
  convert hd using 1
  rw [operator_resolvent_action B 1 R hR x]
  simp only [id_eq, one_smul, map_sub, smul_sub, smul_neg, mul_neg_one, neg_smul]
  abel

theorem op_evolution_gamma_primitive_derivative (B : H →ₗ.[ℂ] H)
    (S : ℝ → H →L[ℂ] H) (hS : OpContractionEvolution B S)
    (R : H →L[ℂ] H) (hR : OpIsResolvent B 1 R) (x : H) (s : ℝ) (hs : 0 ≤ s) :
    HasDerivWithinAt
      (fun t => Real.exp (-t) • S t (R (R x)) +
        t • (Real.exp (-t) • S t (R x)))
      (-((s * Real.exp (-s)) • S s x)) (Ici 0) s := by
  have hd := (op_evolution_shift_derivative B S hS R hR (R x) s hs).add
    ((hasDerivAt_id s).hasDerivWithinAt.smul
      (op_evolution_shift_derivative B S hS R hR x s hs))
  convert hd using 1
  simp only [id_eq, one_smul, smul_neg, smul_smul, one_mul]
  abel

theorem op_evolution_gamma_integrable (B : H →ₗ.[ℂ] H) (S : ℝ → H →L[ℂ] H)
    (hS : OpContractionEvolution B S) (x : H) :
    IntegrableOn (fun s => (s * Real.exp (-s)) • S s x) (Ioi 0) := by
  have hw : IntegrableOn (fun s : ℝ => s * Real.exp (-s)) (Ioi 0) := by
    apply Integrable.of_integral_ne_zero
    have h := operator_gamma_mixing_integral (lam := 0) (le_refl 0)
    rw [show (∫ s : ℝ in Ioi 0, s * Real.exp (-s)) = 1 by simpa using h]
    exact one_ne_zero
  apply (hw.mul_const ‖x‖).mono'
    (((continuous_id.mul continuous_id.neg.rexp).continuousOn.smul
      (hS.continuous_orbit x)).mono Ioi_subset_Ici_self |>.aestronglyMeasurable
        measurableSet_Ioi)
  filter_upwards [ae_restrict_mem measurableSet_Ioi] with s hs
  rw [id_eq, norm_smul, Real.norm_of_nonneg (mul_nonneg hs.le (Real.exp_pos _).le)]
  exact mul_le_mul_of_nonneg_left (hS.contraction s hs.le x)
    (mul_nonneg hs.le (Real.exp_pos _).le)

theorem op_evolution_gamma_primitive_tendsto (B : H →ₗ.[ℂ] H)
    (S : ℝ → H →L[ℂ] H) (hS : OpContractionEvolution B S)
    (R : H →L[ℂ] H) (x : H) :
    Tendsto (fun s => Real.exp (-s) • S s (R (R x)) +
      s • (Real.exp (-s) • S s (R x))) atTop (𝓝 0) := by
  apply squeeze_zero_norm' (a := fun s : ℝ => Real.exp (-s) * ‖R (R x)‖ +
    (s * Real.exp (-s)) * ‖R x‖)
  · filter_upwards [eventually_ge_atTop (0 : ℝ)] with s hs
    apply (norm_add_le _ _).trans
    rw [norm_smul, norm_smul, norm_smul,
      Real.norm_of_nonneg (Real.exp_pos _).le, Real.norm_of_nonneg hs]
    have htwo := mul_le_mul_of_nonneg_left (hS.contraction s hs (R x))
      (mul_nonneg hs ((Real.exp_pos (-s)).le))
    rw [mul_assoc, mul_assoc] at htwo
    exact add_le_add
      (mul_le_mul_of_nonneg_left (hS.contraction s hs (R (R x))) (Real.exp_pos _).le)
      (by simpa only [mul_assoc] using htwo)
  · have hp := (Real.tendsto_pow_mul_exp_neg_atTop_nhds_zero 1).mul_const ‖R x‖
    have he := Real.tendsto_exp_neg_atTop_nhds_zero.mul_const ‖R (R x)‖
    simpa using he.add hp

/-- The strong mixing integral is an actual vector-valued Bochner integral
for every vector. It is the square of the native two-sided shift inverse. -/
theorem op_evolution_strong_gamma_mixing (B : H →ₗ.[ℂ] H)
    (S : ℝ → H →L[ℂ] H) (hS : OpContractionEvolution B S)
    (R : H →L[ℂ] H) (hR : OpIsResolvent B 1 R) (x : H) :
    (∫ s : ℝ in Ioi 0, (s * Real.exp (-s)) • S s x) = R (R x) := by
  have h := integral_Ioi_of_hasDerivAt_of_tendsto
    (f := fun s => Real.exp (-s) • S s (R (R x)) +
      s • (Real.exp (-s) • S s (R x)))
    (f' := fun s => -((s * Real.exp (-s)) • S s x))
    ((op_evolution_gamma_primitive_derivative B S hS R hR x 0 (le_refl 0)).continuousWithinAt)
    (fun s hs => (op_evolution_gamma_primitive_derivative B S hS R hR x s hs.le).hasDerivAt
      (Ici_mem_nhds hs))
    (op_evolution_gamma_integrable B S hS x).neg
    (op_evolution_gamma_primitive_tendsto B S hS R x)
  simpa only [integral_neg, neg_zero, Real.exp_zero, one_smul, zero_smul,
    add_zero, hS.zero_action, zero_sub, neg_inj] using h

/-- An integer eigenvector's evolution is derived from the generator equation,
without assuming a spectral eigenvector action for the evolution. -/
theorem op_evolution_integer_eigenvector_action (B : H →ₗ.[ℂ] H)
    (S : ℝ → H →L[ℂ] H) (hS : OpContractionEvolution B S)
    (n : ℕ) (x : B.domain) (hx : B x = (n : ℂ) • x.val)
    (s : ℝ) (hs : 0 ≤ s) : S s x.val = Real.exp (-(n : ℝ) * s) • x.val := by
  have hd (t : ℝ) (ht : t ∈ Ici 0) :
      HasDerivWithinAt (fun u => Real.exp ((n : ℝ) * u) • S u x.val)
        0 (Ici 0) t := by
    have h := ((hasDerivAt_id t).const_mul (n : ℝ)).exp.hasDerivWithinAt.smul
      (hS.generator_derivative x t ht)
    convert h using 1
    rw [hx, _root_.map_smul]
    simp only [id_eq, mul_one, smul_neg, ← Complex.real_smul, smul_smul]
    module
  have hc : Real.exp ((n : ℝ) * s) • S s x.val = x.val := by
    have h := (convex_Ici (0 : ℝ)).is_const_of_fderivWithin_eq_zero
      (fun t ht => (hd t ht).differentiableWithinAt)
      (fun t ht => by
        rw [(hd t ht).hasFDerivWithinAt.fderivWithin ((uniqueDiffOn_Ici 0) t ht)]
        ext
        simp)
      (show s ∈ Ici 0 from hs) (show (0 : ℝ) ∈ Ici 0 by simp)
    simpa only [mul_zero, Real.exp_zero, one_smul, hS.zero_action] using h
  have h := congrArg (fun y : H => Real.exp (-((n : ℝ) * s)) • y) hc
  simpa only [smul_smul, ← Real.exp_add, neg_add_cancel, Real.exp_zero,
    one_smul, neg_mul] using h

/-- The native two-sided resolvent equations derive its eigenvector action. -/
theorem op_resolvent_integer_eigenvector_action (B : H →ₗ.[ℂ] H)
    (R : H →L[ℂ] H) (hR : OpIsResolvent B 1 R) (n : ℕ)
    (x : B.domain) (hx : B x = (n : ℂ) • x.val) :
    R x.val = ((1 / (1 + (n : ℝ)) : ℝ) : ℂ) • x.val := by
  have hh := hR.left_inverse x
  rw [hx, one_smul] at hh
  have hhe : ((n : ℂ) + 1) • R x.val = x.val := by
    simpa only [add_smul, one_smul, _root_.map_smul, map_add] using hh
  have hn : (n : ℂ) + 1 ≠ 0 := by
    have h : (0 : ℝ) < (n : ℝ) + 1 := by positivity
    exact_mod_cast h.ne'
  have ht := congrArg (fun y : H => ((n : ℂ) + 1)⁻¹ • y) hhe
  simp only [smul_smul, inv_mul_cancel₀ hn, one_smul] at ht
  convert ht using 1
  push_cast
  congr 1
  simp [one_div, add_comm]

/-- Vector-valued integration against the two native Jordan parts. -/
def signedStrongIntegral (μ : SignedMeasure OpNonnegativeRay)
    (f : OpNonnegativeRay → H) : H :=
  (∫ s, f s ∂μ.toJordanDecomposition.posPart) -
    ∫ s, f s ∂μ.toJordanDecomposition.negPart

/-- Strong integration against the native complex measure: the real and
imaginary Jordan integrals of each vector orbit. -/
def complexStrongIntegral (μ : ComplexMeasure OpNonnegativeRay)
    (f : OpNonnegativeRay → H) : H :=
  signedStrongIntegral μ.re f + Complex.I • signedStrongIntegral μ.im f

theorem op_evolution_finite_measure_integrable (B : H →ₗ.[ℂ] H)
    (S : ℝ → H →L[ℂ] H) (hS : OpContractionEvolution B S)
    (μ : Measure OpNonnegativeRay) [IsFiniteMeasure μ] (x : H) :
    Integrable (fun s : OpNonnegativeRay => S s.val x) μ := by
  apply (integrable_const ‖x‖).mono'
    ((hS.continuous_orbit x).restrict.aestronglyMeasurable)
  filter_upwards with s
  exact hS.contraction s.val s.property x

theorem signed_strong_integral_real_test (μ : SignedMeasure OpNonnegativeRay)
    (f : OpNonnegativeRay → ℝ) (x : H) :
    signedStrongIntegral μ (fun s => f s • x) = signedRealIntegral μ f • x := by
  simp only [signedStrongIntegral, signedRealIntegral, integral_smul_const, sub_smul]

theorem complex_strong_integral_real_test (μ : ComplexMeasure OpNonnegativeRay)
    (f : OpNonnegativeRay → ℝ) (x : H) :
    complexStrongIntegral μ (fun s => f s • x) = complexRealIntegral μ f • x := by
  rw [complexStrongIntegral, signed_strong_integral_real_test,
    signed_strong_integral_real_test]
  rw [← algebraMap_smul ℂ (signedRealIntegral μ.re f) x,
    ← algebraMap_smul ℂ (signedRealIntegral μ.im f) x, smul_smul, ← add_smul]
  congr 1
  change (signedRealIntegral μ.re f : ℂ) + Complex.I * (signedRealIntegral μ.im f : ℂ) =
    ⟨signedRealIntegral μ.re f,signedRealIntegral μ.im f⟩
  apply Complex.ext <;> simp

/-- The strong unknown-measure equation on a nonzero integer eigenvector
supplies exactly the scalar integer sample, including the mass sample n=0. -/
theorem op_evolution_complex_mixing_integer_sample (B : H →ₗ.[ℂ] H)
    (S : ℝ → H →L[ℂ] H) (hS : OpContractionEvolution B S)
    (R : H →L[ℂ] H) (hR : OpIsResolvent B 1 R)
    (μ : ComplexMeasure OpNonnegativeRay) (n : ℕ) (x : B.domain)
    (hx : B x = (n : ℂ) • x.val) (hx0 : x.val ≠ 0)
    (hmix : complexStrongIntegral μ (fun s => S s.val x.val) = R (R x.val)) :
    complexRealIntegral μ (nonnegativeLaplaceTest n) =
      (((1 / (1 + (n : ℝ))) ^ 2 : ℝ) : ℂ) := by
  have he : (fun s : OpNonnegativeRay => S s.val x.val) =
      fun s => nonnegativeLaplaceTest n s • x.val := by
    funext s
    exact op_evolution_integer_eigenvector_action B S hS n x hx s.val s.property
  rw [he, complex_strong_integral_real_test] at hmix
  have hRact := op_resolvent_integer_eigenvector_action B R hR n x hx
  rw [hRact, _root_.map_smul, hRact, smul_smul] at hmix
  apply smul_left_injective ℂ hx0
  convert hmix using 1
  push_cast
  simp only [pow_two]

/-- One nonzero eigenvector at each integer, with no completeness or
multiplicity condition, extracts all samples from the actual strong equation
and identifies the original native complex measure. -/
theorem op_evolution_complex_mixing_unique (B : H →ₗ.[ℂ] H)
    (S : ℝ → H →L[ℂ] H) (hS : OpContractionEvolution B S)
    (R : H →L[ℂ] H) (hR : OpIsResolvent B 1 R)
    (μ : ComplexMeasure OpNonnegativeRay)
    (heigen : ∀ n : ℕ, ∃ x : B.domain, x.val ≠ 0 ∧ B x = (n : ℂ) • x.val)
    (hmix : ∀ x : H, complexStrongIntegral μ (fun s => S s.val x) = R (R x)) :
    μ = nonnegativeGammaComplexMeasure := by
  apply operator_complex_gamma_mixing_characterization
  intro n
  obtain ⟨x,hx0,hx⟩ := heigen n
  exact op_evolution_complex_mixing_integer_sample B S hS R hR μ n x hx hx0 (hmix x.val)

end
end Sigma
