#!/usr/bin/env python3

from pathlib import Path
import argparse
from collections import Counter
from datetime import datetime, timezone
import hashlib
import json
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
REPORT = REPO / "audits" / "axiom-dependencies.json"
ALLOWED_AXIOMS = {"propext", "Classical.choice", "Quot.sound"}


def strip_lean_comments(text: str) -> str:
    """Remove Lean line comments and nested block comments."""
    out = []
    i = 0
    depth = 0

    while i < len(text):
        if depth == 0 and text.startswith("--", i):
            end = text.find("\n", i)
            if end == -1:
                break
            out.append("\n")
            i = end + 1
            continue

        if text.startswith("/-", i):
            depth += 1
            i += 2
            continue

        if depth > 0 and text.startswith("-/", i):
            depth -= 1
            i += 2
            continue

        if depth == 0:
            out.append(text[i])
        elif text[i] == "\n":
            out.append("\n")

        i += 1

    return "".join(out)


def source_audit() -> None:
    forbidden = re.compile(r"\b(sorry|admit|sorryAx)\b")
    project_axiom = re.compile(r"\baxiom\b")
    violations = []

    for path in sorted(ROOT.glob("*.lean")):
        code = strip_lean_comments(path.read_text())

        for lineno, line in enumerate(code.splitlines(), 1):
            match = forbidden.search(line)
            if match:
                violations.append(
                    f"{path.name}:{lineno}: {match.group(1)}"
                )
            if project_axiom.search(line):
                violations.append(f"{path.name}:{lineno}: project axiom declaration")

    if violations:
        print("Proof escapes found:")
        print("\n".join(violations))
        raise SystemExit(1)

    print("Source audit: no sorry, admit, sorryAx, or project axiom declarations.")


def run(command: list[str], log: Path | None = None) -> str:
    print("+", " ".join(command), flush=True)

    proc = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    if log is not None:
        log.parent.mkdir(parents=True, exist_ok=True)
        log.write_text(proc.stdout)
        print(f"Full output: {log.relative_to(REPO)}", flush=True)
    else:
        print(proc.stdout, end="")

    if proc.returncode != 0:
        if log is not None:
            print(proc.stdout, end="")
        raise SystemExit(proc.returncode)

    return proc.stdout


def source_fingerprints() -> dict[str, str]:
    paths = sorted(ROOT.glob("*.lean")) + [
        ROOT / "lean-toolchain", ROOT / "lake-manifest.json",
        ROOT / "Build.py", ROOT / "Verify.py",
    ]
    return {str(p.relative_to(REPO)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in paths}


def expected_declarations() -> list[str]:
    return re.findall(r"^#print axioms (\S+)\s*$",
                      strip_lean_comments((ROOT / "SigmaAxioms.lean").read_text()), re.M)


def parse_axioms(output: str) -> dict[str, list[str]]:
    pattern = r"'([^']+)' (?:depends on axioms:\s*\[([^]]*)\]|does not depend on any axioms)"
    matches = re.findall(pattern, output)
    expected = Counter(expected_declarations())
    actual = Counter(name for name, _ in matches)
    if not expected or actual != expected:
        raise SystemExit(f"Axiom report mismatch: missing={list((expected-actual).elements())}; "
                         f"unexpected={list((actual-expected).elements())}")
    if any(count != 1 for count in expected.values()):
        raise SystemExit("Duplicate declarations in SigmaAxioms.lean")
    result = {name: sorted(set(axioms.replace(',', ' ').split()))
              for name, axioms in matches}
    for name, axioms in result.items():
        unexpected = set(axioms) - ALLOWED_AXIOMS
        if unexpected:
            raise SystemExit(f"Unexpected proof axioms for {name}: {sorted(unexpected)}")
    return dict(sorted(result.items()))


def report_markdown(report: dict) -> str:
    return f"""# Build and axiom-dependency verification

Generated by `python3 lean/Verify.py --write-report`. The
[machine-readable report](axiom-dependencies.json) records source fingerprints
and the transitive axiom dependencies of every declaration requested by
[`SigmaAxioms.lean`](../lean/SigmaAxioms.lean).

| Check | Recorded result |
| --- | --- |
| Completed (UTC) | {report['completed_at_utc']} |
| Full `SigmaFormalization` library build | PASS |
| Source scan for `sorry`, `admit`, `sorryAx`, project axiom declarations | PASS; none found |
| Requested axiom reports | {report['expected_checks']:,} |
| Received reports / distinct declarations | {report['reported_checks']:,} / {report['distinct_declarations']:,} |
| Missing, unexpected or duplicate reports | 0 |
| Observed axiom dependencies | {', '.join('`'+a+'`' for a in report['observed_axioms'])} |
| Unexpected axioms | 0 |

## Scope

This is the full **committed axiom-check list**, not an enumeration of every
declaration in the project or mathlib. The separately generated
[proved inventory](proved-inventory.md) counts declarations mapped to paper
items; those counts have a different scope.

Mathematical hypotheses, including the supplied Itô/Lévy and topological
foundations, remain theorem parameters. An axiom-dependency check does not
discharge those hypotheses or establish paper-to-Lean semantic coverage.

The JSON fingerprints identify the verified working-tree sources. Its base
commit is provenance, not a claim that uncommitted changes were absent.
`python3 lean/Verify.py --check-report` checks the saved report against those
sources and this rendering; it does not rerun Lean. To repeat compilation and
the full axiom scan, run `python3 lean/Verify.py` (or add `--write-report` to
refresh the committed evidence). Raw logs are local build artifacts in
`lean/.lake/build.log` and `lean/.lake/axioms.log`.
"""


def check_report() -> None:
    report = json.loads(REPORT.read_text())
    if report.get("source_sha256") != source_fingerprints():
        raise SystemExit("Verification report is stale for the current sources.")
    expected = expected_declarations()
    dependencies = report.get("declaration_axioms", {})
    observed = sorted({a for values in dependencies.values() for a in values})
    if (not expected or len(expected) != len(set(expected))
            or set(dependencies) != set(expected)
            or any(report.get(k) != len(expected) for k in
                   ("expected_checks", "reported_checks", "distinct_declarations"))
            or set(observed) - ALLOWED_AXIOMS
            or observed != report.get("observed_axioms")
            or report.get("verifier_exit_status") != 0
            or not report.get("source_audit_passed")
            or not report.get("full_library_build_passed")
            or any(report.get(k) != [] for k in
                   ("missing_reports", "unexpected_reports", "unexpected_axioms"))):
        raise SystemExit("Inconsistent verification report.")
    if REPORT.with_suffix(".md").read_text() != report_markdown(report):
        raise SystemExit("Stale axiom-dependencies.md rendering.")
    print(f"Saved verification report: PASS; {len(expected)} declaration reports; sources match.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build and audit the Lean development.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write-report", action="store_true", help="save fresh JSON/Markdown evidence")
    mode.add_argument("--check-report", action="store_true", help="check saved evidence without rerunning Lean")
    args = parser.parse_args()
    source_audit()
    if args.check_report:
        check_report()
        return

    before = source_fingerprints()

    run([sys.executable, str(ROOT / "Build.py")])

    axiom_output = run(
        ["lake", "env", "lean", "SigmaAxioms.lean"], ROOT / ".lake" / "axioms.log"
    )

    if "sorryAx" in axiom_output:
        print("Axiom audit contains sorryAx.", file=sys.stderr)
        raise SystemExit(1)

    dependencies = parse_axioms(axiom_output)
    if source_fingerprints() != before:
        raise SystemExit("Sources changed during verification; no report written.")
    print(f"Axiom reports: {len(dependencies)} matched; only permitted foundations.")
    if args.write_report:
        report = {
            "base_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip(),
            "completed_at_utc": datetime.now(timezone.utc).isoformat(),
            "command": "python3 lean/Verify.py --write-report",
            "working_directory": ".",
            "verifier_exit_status": 0,
            "source_audit_passed": True,
            "full_library_build_passed": True,
            "axiom_scan_command": "lake env lean SigmaAxioms.lean",
            "axiom_scan_source": "lean/SigmaAxioms.lean",
            "axiom_scan_source_sha256": before["lean/SigmaAxioms.lean"],
            "expected_checks": len(expected_declarations()),
            "reported_checks": len(dependencies),
            "distinct_declarations": len(dependencies),
            "missing_reports": [], "unexpected_reports": [],
            "allowed_axioms": sorted(ALLOWED_AXIOMS),
            "observed_axioms": sorted({a for values in dependencies.values() for a in values}),
            "unexpected_axioms": [],
            "axiom_output_sha256": hashlib.sha256(axiom_output.encode()).hexdigest(),
            "lean_toolchain": (ROOT / "lean-toolchain").read_text().strip(),
            "scope": "Full SigmaAxioms declaration list, full library build, and source admission audit. Supplied mathematical foundations remain theorem parameters.",
            "source_sha256": before,
            "declaration_axioms": dependencies,
        }
        REPORT.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n")
        REPORT.with_suffix(".md").write_text(report_markdown(report))
        print("Wrote audits/axiom-dependencies.json and .md.")

    print()
    print("Verification completed successfully.")


if __name__ == "__main__":
    main()
